# Generated by Django 3.1.6 on 2023-03-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translation',
            name='format',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='translations.format'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='destination_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destination_translations', to='translations.language'),
        ),
        migrations.AlterField(
            model_name='translation',
            name='origin_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='origin_translations', to='translations.language'),
        ),
    ]
