# Generated by Django 4.1.3 on 2023-03-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0003_remove_format_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='origin_content',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='resultat_content',
            new_name='translation',
        ),
        migrations.RenameField(
            model_name='translation',
            old_name='destination_language',
            new_name='translator',
        ),
        migrations.RemoveField(
            model_name='translation',
            name='origin_language',
        ),
    ]
