# Generated by Django 4.1.3 on 2023-03-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translations', '0004_rename_origin_content_translation_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='translation',
            old_name='translator',
            new_name='language',
        ),
    ]
